version: "3.8"

services:
  db:
    container_name: mysqldb
    ports:
      - "3306"
    image: mysql:latest
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: apiDB
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 4200:4200
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/home/appdev/appbackend
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: --reload
    environment:
      PROJECT_NAME: ${PROJECT_NAME:-rentalServiceAPI}
      SECRET_KEY: ${SECRET_KEY:-SecretDevKey}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS:-["http://localhost", "http://localhost:4200", "http://localhost:3306"]}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      MYSQL_SERVER: ${MYSQL_SERVER:-http://localhost:59653}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-my-secret-pw}
      MYSQL_DB: ${MYSQL_DB:-apiDB}
